### ISSUE TITLE
Add more specific error message when trying to access http repositories

### ISSUE THREAD

**Issue by chriswainformatik** [eclipse-jgit/jgit#18]
### Description

When trying to access a repository via http, the error message should be something like: "You cannot access repositories via http." instead of "Authentication is required but no CredentialsProvider has been registered."

There are probably more cases than http/https which are covered by this error.

### Motivation

It helps people finding bugs in their software and/or server configuration.

### Additional context

I was using BlueJ and my own git server which I misconfigured so that it only used http instead of https. When I tried to checkout a repository from my server I only got the error message mentioned above. It would have saved me a lot of time finding my mistake if the error message had been referring to what the actual problem was.

**Comment by tomaswolf** [comment]
JGit has no such restriction. It's BlueJ that implements it that way, and the message you got ("Authentication is required but no CredentialsProvider has been registered.") is in fact spot on.

BlueJ sets a CredentialsProvider [only if the protocol is "ssh" or "https"](https://github.com/k-pet-group/BlueJ-Greenfoot/blob/5c31821dfeb1decc08110f72004f483c1e33cca0/bluej/src/main/java/bluej/groupwork/git/GitCommand.java#L69). It does not do so for plain old "http", so you can do only anonymous clones over plain "http".

Apart from that I notice that BlueJ
* depends on the [very old JGit 4.9.0.201710071750-r](https://github.com/k-pet-group/BlueJ-Greenfoot/blob/5c31821dfeb1decc08110f72004f483c1e33cca0/bluej/build.gradle#L19).
* always [disables host key checking](https://github.com/k-pet-group/BlueJ-Greenfoot/blob/5c31821dfeb1decc08110f72004f483c1e33cca0/bluej/src/main/java/bluej/groupwork/git/GitCommand.java#L77) for SSH connections, which is bad since it makes one susceptible to mad-in-the-middle attacks.
* sets an [SSH session factory](https://github.com/k-pet-group/BlueJ-Greenfoot/blob/5c31821dfeb1decc08110f72004f483c1e33cca0/bluej/src/main/java/bluej/groupwork/git/GitCommand.java#L71) even for HTTPS connections, which is nonsense.

**Comment by tomaswolf** [comment]
Not a problem in JGit.

**Comment by chriswainformatik** [comment]
Thank you for clarification, I will talk to the BlueJ team again.
