### ISSUE TITLE
JGit Compatability with Jakarta EE10

### ISSUE THREAD

**Issue by ekennedy80** [eclipse-jgit/jgit#19]
### Description

Currently, JGit uses javax.* making it incompatible with newer jakarta.*.

### Motivation

In order to allow other web applications that use JGit the ability to use newer jakarata libs, JGit needs to move away from javax to jakarta.

**Comment by mchoubby** [comment]
when will this enhancement be achieved please ? it's blocking us from upgrading to the last major version of spring boot

**Comment by davido** [comment]
Here is the pending change to migrate to Jetty 11.0 and Servlet-API 5.0: [1].

[1] https://review.gerrithub.io/c/eclipse-jgit/jgit/+/189213

**Comment by tomjo** [comment]
I see this change is merged ❤️  Is there a planning for the next release version?

**Comment by msohn** [comment]
JGit releases following the calendar of the Eclipse IDE simultaneous release,
see https://github.com/eclipse-simrel/.github/blob/main/wiki/Simultaneous_Release.md

JGit releases (existing and planned) are listed here https://projects.eclipse.org/projects/technology.jgit
- The next release 6.10 is planned to be shipped with Eclipse IDE 2024-06 on June 12, 2024.
- We plan to ship the update to Jetty 12 with JGit 7.0 with Eclipse IDE 2024-06 on Sep 11, 2024.

**Comment by BaumiCoder** [comment]
I try to use the 6.10 version in [Artemis](https://github.com/ls1intum/Artemis), but jgit http server still contains `javax` instead of `jakarta` for the imports.

The switch was performed with commit https://github.com/eclipse-jgit/jgit/commit/a31580f459b0ae24b51c519ce71ad728ff156c8f on May 2, 2024. Althougth the [tag of 6.10](https://github.com/eclipse-jgit/jgit/releases/tag/v6.10.0.202406032230-r) from Jun 4, 2024 does not contain this change. For example `GitServlet.java` still contains `javax` [in this tag](https://github.com/eclipse-jgit/jgit/blob/23aaf83e8b4fa38640eeb6206e909f23eaba2994/org.eclipse.jgit.http.server/src/org/eclipse/jgit/http/server/GitServlet.java).

@msohn I would have understood your comment to mean that this change should be included in 6.10. Am I wrong here?
